version: '3.9'

services:

  db:
    image: postgres:12.4
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgresdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    env_file:
      - .env

volumes:
  postgres_data:
