version: '3.9'

services:

  db:
    image: postgres:12.4
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

  app:
    image: gorsheninnikolay/test_task_bewise
    ports:
      - "5000:5000"
    container_name: application
    command: >
      bash -c "cd test_task && flask run --host 0.0.0.0 --port 5000"
    environment:
      - URL_DB=db:5432
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
