"""empty message

Revision ID: 5b8f28f665b4
Revises: 8bbe8e55c02a
Create Date: 2022-05-03 17:34:12.861312

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5b8f28f665b4'
down_revision = '8bbe8e55c02a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('created_date', sa.Date(), nullable=True))
    op.drop_column('document', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('document', 'created_date')
    # ### end Alembic commands ###
