"""document table

Revision ID: 83b55471f52e
Revises: 
Create Date: 2022-05-03 16:38:28.956557

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '83b55471f52e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    # ### end Alembic commands ###
