"""empty message

Revision ID: ea76a010cfeb
Revises: 83b55471f52e
Create Date: 2022-05-03 17:08:14.461889

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ea76a010cfeb'
down_revision = '83b55471f52e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('text_question', sa.Text(), nullable=True))
    op.add_column('document', sa.Column('text_answer', sa.Text(), nullable=True))
    op.add_column('document', sa.Column('date', sa.Date(), nullable=True))
    op.drop_column('document', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('document', 'date')
    op.drop_column('document', 'text_answer')
    op.drop_column('document', 'text_question')
    # ### end Alembic commands ###
